/**
 * This file was generated by the @pikku/cli
 */
import { pikkuState } from '@pikku/core'
pikkuState('rpc', 'meta', {
  "timeSinceOpened": {
    "pikkuFuncName": "pikkuFn_src_http_sse_functions_ts_L6C3",
    "exposed": false
  },
  "welcomeToPikku": {
    "pikkuFuncName": "pikkuFn_src_http_functions_ts_L3C58",
    "exposed": false
  },
  "helloWorld": {
    "pikkuFuncName": "pikkuFn_src_http_functions_ts_L7C54",
    "exposed": false
  },
  "rpcTest": {
    "pikkuFuncName": "pikkuFn_src_rpc_functions_ts_L4C3",
    "exposed": false
  },
  "rpcCaller": {
    "pikkuFuncName": "pikkuFn_src_rpc_functions_ts_L16C3",
    "exposed": false
  }
})