/**
 * This file was generated by @pikku/cli@0.12.0
 */
import { pikkuState } from '@pikku/core'
import { ScheduledTasksMeta } from '@pikku/core/scheduler'
import metaData from './pikku-schedulers-wirings-meta.gen.json' with { type: 'json' }

pikkuState(null, 'scheduler', 'meta', metaData as ScheduledTasksMeta)