/**
 * This file was generated by @pikku/cli@0.12.0
 */
/**
 * Agent type map with output types for each agent
 */




export type ListTodosInput = {
    completed?: boolean | undefined;
    priority?: ("low" | "medium" | "high") | undefined;
    tag?: string | undefined;
    /** User ID (uses demo user if not provided) */
    userId?: (string | null) | undefined;
}
export type ListTodosOutput = {
    todos: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    }[];
    total: number;
}
export type GetTodoInput = {
    /** Todo ID */
    id: string;
}
export type GetTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    } | null;
}
export type CreateTodoInput = {
    title: string;
    description?: string | undefined;
    priority: ("low" | "medium" | "high") | undefined;
    dueDate?: string | undefined;
    tags: string[] | undefined;
    /** User ID (uses demo user if not provided) */
    userId?: (string | null) | undefined;
}
export type CreateTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    };
}
export type UpdateTodoInput = {
    /** Todo ID */
    id: string;
    title?: string | undefined;
    description?: string | undefined;
    priority?: ("low" | "medium" | "high") | undefined;
    dueDate?: string | undefined;
    tags?: string[] | undefined;
    completed?: boolean | undefined;
}
export type UpdateTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    } | null;
    success: boolean;
}
export type DeleteTodoInput = {
    /** Todo ID */
    id: string;
}
export type DeleteTodoOutput = {
    success: boolean;
}
export type CompleteTodoInput = {
    /** Todo ID */
    id: string;
}
export type CompleteTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    } | null;
    success: boolean;
}
export type TodoAssistantOutput = {
    message: string;
    todos?: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    }[] | undefined;
}
export type LoginInput = {
    username: string;
    password: string;
}
export type LoginOutput = {
    token: string;
    user: {
        id: string;
        username: string;
        email: string;
    };
}
export type GetMeInput = {}
export type GetMeOutput = {
    user: {
        id: string;
        username: string;
        email: string;
    };
}
export type LogoutInput = {}
export type LogoutOutput = {
    success: boolean;
}
export type TestEventTriggerInput = { eventName: string; }
export type TestEventTriggerOutput = { payload: string; }
export type OnTestEventInput = {
    payload: string;
}
export type OnTestEventOutput = {
    payload: string;
}
export type RpcCallerInput = { rpcName: string; data?: unknown; }

interface AgentHandler<O> {
    output: O;
}

export type AgentMap = {
  readonly 'todoAssistant': AgentHandler<TodoAssistantOutput>,
  readonly 'dailyPlanner': AgentHandler<string>,
  readonly 'mainRouter': AgentHandler<string>,
};
