/**
 * This file was generated by @pikku/cli@0.12.15
 */
/**
 * Agent type map with output types for each agent
 */




export type AgentApproveCallerInput = { agentName: string; runId: string; approvals: { toolCallId: string; approved: boolean; }[]; }
export type AgentCallerInput = { agentName: string; message: string; threadId: string; resourceId: string; }
export type AgentResumeCallerInput = { agentName: string; runId: string; toolCallId: string; approved: boolean; }
export type AgentStreamCallerInput = { agentName: string; message: string; threadId: string; resourceId: string; }
export type CompleteTodoInput = {
    /** Todo ID */
    id: string;
}
export type CompleteTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    } | null;
    success: boolean;
}
export type CreateTodoInput = {
    title: string;
    description?: string | undefined;
    priority: ("low" | "medium" | "high") | undefined;
    dueDate?: string | undefined;
    tags: string[] | undefined;
    /** User ID (uses demo user if not provided) */
    userId?: (string | null) | undefined;
}
export type CreateTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    };
}
export type DeleteTodoInput = {
    /** Todo ID */
    id: string;
}
export type DeleteTodoOutput = {
    success: boolean;
}
export type GetTodoInput = {
    /** Todo ID */
    id: string;
}
export type GetTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    } | null;
}
export type HttpOptionsRpcRpcNameInput = { rpcName: string; }
export type ListTodosInput = {
    completed?: boolean | undefined;
    priority?: ("low" | "medium" | "high") | undefined;
    tag?: string | undefined;
    /** User ID (uses demo user if not provided) */
    userId?: (string | null) | undefined;
}
export type ListTodosOutput = {
    todos: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    }[];
    total: number;
}
export type OnTestEventInput = {
    payload: string;
}
export type OnTestEventOutput = {
    payload: string;
}
export type RpcCallerInput = { rpcName: string; data?: unknown; }
export type TestEventTriggerInput = { eventName: string; }
export type TestEventTriggerOutput = { payload: string; }
export type TodoAssistantOutput = {
    message: string;
    todos?: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    }[] | undefined;
}
export type UpdateTodoInput = {
    /** Todo ID */
    id: string;
    title?: string | undefined;
    description?: string | undefined;
    priority?: ("low" | "medium" | "high") | undefined;
    dueDate?: string | undefined;
    tags?: string[] | undefined;
    completed?: boolean | undefined;
}
export type UpdateTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    } | null;
    success: boolean;
}

interface AgentHandler<O> {
    output: O;
}

export type AgentMap = {
  readonly 'todoAssistant': AgentHandler<TodoAssistantOutput>,
  readonly 'dailyPlanner': AgentHandler<string>,
  readonly 'mainRouter': AgentHandler<string>,
};
