/**
 * This file was generated by @pikku/cli@0.12.0
 */
/**
 * This provides the structure needed for typescript to be aware of routes and their return types
 */





export type ListTodosInput = {
    completed?: boolean | undefined;
    priority?: ("low" | "medium" | "high") | undefined;
    tag?: string | undefined;
    /** User ID (uses demo user if not provided) */
    userId?: (string | null) | undefined;
}
export type ListTodosOutput = {
    todos: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    }[];
    total: number;
}
export type GetTodoInput = {
    /** Todo ID */
    id: string;
}
export type GetTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    } | null;
}
export type CreateTodoInput = {
    title: string;
    description?: string | undefined;
    priority: ("low" | "medium" | "high") | undefined;
    dueDate?: string | undefined;
    tags: string[] | undefined;
    /** User ID (uses demo user if not provided) */
    userId?: (string | null) | undefined;
}
export type CreateTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    };
}
export type UpdateTodoInput = {
    /** Todo ID */
    id: string;
    title?: string | undefined;
    description?: string | undefined;
    priority?: ("low" | "medium" | "high") | undefined;
    dueDate?: string | undefined;
    tags?: string[] | undefined;
    completed?: boolean | undefined;
}
export type UpdateTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    } | null;
    success: boolean;
}
export type DeleteTodoInput = {
    /** Todo ID */
    id: string;
}
export type DeleteTodoOutput = {
    success: boolean;
}
export type CompleteTodoInput = {
    /** Todo ID */
    id: string;
}
export type CompleteTodoOutput = {
    todo: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    } | null;
    success: boolean;
}
export type TodoAssistantOutput = {
    message: string;
    todos?: {
        id: string;
        userId: string;
        title: string;
        description?: string | undefined;
        completed: boolean;
        priority: "low" | "medium" | "high";
        dueDate?: string | undefined;
        tags: string[];
        createdAt: string;
        updatedAt: string;
    }[] | undefined;
}
export type LoginInput = {
    username: string;
    password: string;
}
export type LoginOutput = {
    token: string;
    user: {
        id: string;
        username: string;
        email: string;
    };
}
export type GetMeInput = {}
export type GetMeOutput = {
    user: {
        id: string;
        username: string;
        email: string;
    };
}
export type LogoutInput = {}
export type LogoutOutput = {
    success: boolean;
}
export type TestEventTriggerInput = { eventName: string; }
export type TestEventTriggerOutput = { payload: string; }
export type OnTestEventInput = {
    payload: string;
}
export type OnTestEventOutput = {
    payload: string;
}
export type AgentCallerInput = { agentName: string; message: string; threadId: string; resourceId: string; }
export type AgentStreamCallerInput = { agentName: string; message: string; threadId: string; resourceId: string; }
export type AgentApproveCallerInput = { agentName: string; runId: string; approvals: { toolCallId: string; approved: boolean; }[]; }
export type HttpOptionsRpcAgentAgentNameInput = { agentName: string; }
export type HttpOptionsRpcAgentAgentNameStreamInput = { agentName: string; }
export type RpcCallerInput = { rpcName: string; data?: unknown; }
export type HttpOptionsRpcRpcNameInput = { rpcName: string; }

// The '& {}' is a workaround for not directly refering to a type since it confuses typescript
export type HttpOptionsRpcAgentAgentNameInputParams = Pick<HttpOptionsRpcAgentAgentNameInput, 'agentName'> & {}
export type HttpOptionsRpcAgentAgentNameInputBody = Omit<HttpOptionsRpcAgentAgentNameInput, 'agentName'> & {}
export type AgentCallerInputParams = Pick<AgentCallerInput, 'agentName'> & {}
export type AgentCallerInputBody = Omit<AgentCallerInput, 'agentName'> & {}
export type HttpOptionsRpcAgentAgentNameStreamInputParams = Pick<HttpOptionsRpcAgentAgentNameStreamInput, 'agentName'> & {}
export type HttpOptionsRpcAgentAgentNameStreamInputBody = Omit<HttpOptionsRpcAgentAgentNameStreamInput, 'agentName'> & {}
export type AgentStreamCallerInputParams = Pick<AgentStreamCallerInput, 'agentName'> & {}
export type AgentStreamCallerInputBody = Omit<AgentStreamCallerInput, 'agentName'> & {}
export type AgentApproveCallerInputParams = Pick<AgentApproveCallerInput, 'agentName'> & {}
export type AgentApproveCallerInputBody = Omit<AgentApproveCallerInput, 'agentName'> & {}
export type LoginInputBody = LoginInput & {}
export type LogoutInputBody = LogoutInput & {}
export type GetMeInputBody = GetMeInput & {}
export type HttpOptionsRpcRpcNameInputParams = Pick<HttpOptionsRpcRpcNameInput, 'rpcName'> & {}
export type HttpOptionsRpcRpcNameInputBody = Omit<HttpOptionsRpcRpcNameInput, 'rpcName'> & {}
export type RpcCallerInputParams = Pick<RpcCallerInput, 'rpcName'> & {}
export type RpcCallerInputBody = Omit<RpcCallerInput, 'rpcName'> & {}
export type ListTodosInputBody = ListTodosInput & {}
export type GetTodoInputParams = Pick<GetTodoInput, 'id'> & {}
export type GetTodoInputBody = Omit<GetTodoInput, 'id'> & {}
export type CreateTodoInputBody = CreateTodoInput & {}
export type UpdateTodoInputParams = Pick<UpdateTodoInput, 'id'> & {}
export type UpdateTodoInputBody = Omit<UpdateTodoInput, 'id'> & {}
export type DeleteTodoInputParams = Pick<DeleteTodoInput, 'id'> & {}
export type DeleteTodoInputBody = Omit<DeleteTodoInput, 'id'> & {}
export type CompleteTodoInputParams = Pick<CompleteTodoInput, 'id'> & {}
export type CompleteTodoInputBody = Omit<CompleteTodoInput, 'id'> & {}

interface HTTPWiringHandler<I, O> {
    input: I;
    output: O;
}

export type HTTPWiringsMap = {
  readonly '/rpc/agent/:agentName/stream': {
    readonly GET: HTTPWiringHandler<AgentStreamCallerInput, null>,
    readonly OPTIONS: HTTPWiringHandler<HttpOptionsRpcAgentAgentNameStreamInput, unknown>,
  },
  readonly '/auth/me': {
    readonly GET: HTTPWiringHandler<GetMeInput, GetMeOutput>,
  },
  readonly '/todos': {
    readonly GET: HTTPWiringHandler<ListTodosInput, ListTodosOutput>,
    readonly POST: HTTPWiringHandler<CreateTodoInput, CreateTodoOutput>,
  },
  readonly '/todos/:id': {
    readonly GET: HTTPWiringHandler<GetTodoInput, GetTodoOutput>,
    readonly PUT: HTTPWiringHandler<UpdateTodoInput, UpdateTodoOutput>,
    readonly DELETE: HTTPWiringHandler<DeleteTodoInput, DeleteTodoOutput>,
  },
  readonly '/rpc/agent/:agentName': {
    readonly POST: HTTPWiringHandler<AgentCallerInput, null>,
    readonly OPTIONS: HTTPWiringHandler<HttpOptionsRpcAgentAgentNameInput, unknown>,
  },
  readonly '/rpc/agent/:agentName/approve': {
    readonly POST: HTTPWiringHandler<AgentApproveCallerInput, null>,
  },
  readonly '/auth/login': {
    readonly POST: HTTPWiringHandler<LoginInput, LoginOutput>,
  },
  readonly '/auth/logout': {
    readonly POST: HTTPWiringHandler<LogoutInput, LogoutOutput>,
  },
  readonly '/rpc/:rpcName': {
    readonly POST: HTTPWiringHandler<RpcCallerInput, null>,
    readonly OPTIONS: HTTPWiringHandler<HttpOptionsRpcRpcNameInput, unknown>,
  },
  readonly '/todos/:id/complete': {
    readonly POST: HTTPWiringHandler<CompleteTodoInput, CompleteTodoOutput>,
  },
};

export type HTTPWiringHandlerOf<HTTPWiring extends keyof HTTPWiringsMap, Method extends keyof HTTPWiringsMap[HTTPWiring]> =
    HTTPWiringsMap[HTTPWiring][Method] extends { input: infer I; output: infer O }
        ? HTTPWiringHandler<I, O>
        : never;

export type HTTPWiringsWithMethod<Method extends string> = {
  [HTTPWiring in keyof HTTPWiringsMap]: Method extends keyof HTTPWiringsMap[HTTPWiring] ? HTTPWiring : never;
}[keyof HTTPWiringsMap];
  