/**
 * This file was generated by the @pikku/cli
 */
import { pikkuState } from '@pikku/core'
pikkuState('http', 'meta', {
  "get": {
    "/": {
      "pikkuFuncName": "welcomeToPikku",
      "route": "/",
      "method": "get",
      "tags": [
        "welcome"
      ]
    },
    "/hello-world": {
      "pikkuFuncName": "helloWorld",
      "route": "/hello-world",
      "method": "get",
      "tags": [
        "hello"
      ]
    }
  },
  "post": {
    "/rpc": {
      "pikkuFuncName": "rpcCaller",
      "route": "/rpc",
      "method": "post"
    }
  },
  "put": {},
  "delete": {},
  "head": {},
  "patch": {},
  "options": {}
})