/**
 * This file was generated by @pikku/cli@0.12.0
 */
/* The files with an wireHTTP function call */
import '../../src/wirings/agent.wiring.gen.js'
import '../../src/wirings/auth.wiring.js'
import '../../src/wirings/rpc.wiring.js'
import '../../src/wirings/todos.http.js'