/**
 * This file was generated by @pikku/cli@0.12.15
 */
/* The files with an wireHTTP function call */
import '../../pikku/agent.wiring.gen.js'
import '../../src/wirings/rpc.wiring.js'
import '../../src/wirings/todos.http.js'