/**
 * This file was generated by the @pikku/cli
 */
/* Import and register RPCs */
import { addFunction } from '@pikku/core'
import { helloWorld } from '../../src/http.functions.js'
import { rpcCaller } from '../../src/rpc.functions.js'
import { rpcTest } from '../../src/rpc.functions.js'
import { timeSinceOpened } from '../../src/http-sse.functions.js'
import { welcomeToPikku } from '../../src/http.functions.js'

addFunction('helloWorld', { func: helloWorld })
addFunction('rpcCaller', { func: rpcCaller })
addFunction('rpcTest', { func: rpcTest })
addFunction('timeSinceOpened', { func: timeSinceOpened })
addFunction('welcomeToPikku', { func: welcomeToPikku })