/**
 * This file was generated by @pikku/cli@0.11.1
 */
import { pikkuState } from '@pikku/core'
pikkuState('function', 'meta', {
  "welcomeToPikku": {
    "pikkuFuncName": "welcomeToPikku",
    "inputSchemaName": null,
    "outputSchemaName": "string"
  },
  "helloWorld": {
    "pikkuFuncName": "helloWorld",
    "inputSchemaName": null,
    "outputSchemaName": "string"
  },
  "rpcTest": {
    "pikkuFuncName": "rpcTest",
    "inputSchemaName": "RpcTestInput",
    "outputSchemaName": null,
    "expose": true
  },
  "rpcCaller": {
    "pikkuFuncName": "rpcCaller",
    "inputSchemaName": "RpcCallerInput",
    "outputSchemaName": null
  },
  "pikkuFn_rpc_wiring_ts_L35C9": {
    "pikkuFuncName": "pikkuFn_rpc_wiring_ts_L35C9",
    "inputSchemaName": null,
    "outputSchemaName": null
  }
})