/**
 * This file was generated by the @pikku/cli
 */
import { pikkuState } from '@pikku/core'
pikkuState('function', 'meta', {
  "pikkuFn_src_http_sse_functions_ts_L6C3": {
    "pikkuFuncName": "pikkuFn_src_http_sse_functions_ts_L6C3",
    "name": "timeSinceOpened",
    "services": {
      "optimized": true,
      "services": [
        "channel"
      ]
    },
    "schemaName": null,
    "inputs": [],
    "outputs": [
      "TimeSinceOpenedOutput"
    ]
  },
  "pikkuFn_src_http_functions_ts_L3C58": {
    "pikkuFuncName": "pikkuFn_src_http_functions_ts_L3C58",
    "name": "welcomeToPikku",
    "services": {
      "optimized": true,
      "services": []
    },
    "schemaName": null,
    "inputs": [],
    "outputs": [
      "string"
    ]
  },
  "pikkuFn_src_http_functions_ts_L7C54": {
    "pikkuFuncName": "pikkuFn_src_http_functions_ts_L7C54",
    "name": "helloWorld",
    "services": {
      "optimized": true,
      "services": []
    },
    "schemaName": null,
    "inputs": [],
    "outputs": [
      "string"
    ]
  },
  "pikkuFn_src_rpc_functions_ts_L4C3": {
    "pikkuFuncName": "pikkuFn_src_rpc_functions_ts_L4C3",
    "name": "rpcTest",
    "services": {
      "optimized": true,
      "services": [
        "logger",
        "rpc"
      ]
    },
    "schemaName": "RpcTestInput",
    "inputs": [
      "RpcTestInput"
    ],
    "outputs": []
  },
  "pikkuFn_src_rpc_functions_ts_L16C3": {
    "pikkuFuncName": "pikkuFn_src_rpc_functions_ts_L16C3",
    "name": "rpcCaller",
    "services": {
      "optimized": true,
      "services": [
        "rpc"
      ]
    },
    "schemaName": "RpcCallerInput",
    "inputs": [
      "RpcCallerInput"
    ],
    "outputs": []
  }
})