/**
 * This file was generated by @pikku/cli@0.11.1
 */
import { pikkuState } from '@pikku/core'
pikkuState('function', 'meta', {
  "welcomeToPikku": {
    "pikkuFuncName": "welcomeToPikku",
    "name": "welcomeToPikku",
    "services": {
      "optimized": true,
      "services": []
    },
    "inputSchemaName": null,
    "outputSchemaName": "string",
    "inputs": [],
    "outputs": [
      "string"
    ],
    "isDirectFunction": true
  },
  "helloWorld": {
    "pikkuFuncName": "helloWorld",
    "name": "helloWorld",
    "services": {
      "optimized": true,
      "services": []
    },
    "inputSchemaName": null,
    "outputSchemaName": "string",
    "inputs": [],
    "outputs": [
      "string"
    ],
    "isDirectFunction": true
  },
  "rpcTest": {
    "pikkuFuncName": "rpcTest",
    "name": "rpcTest",
    "services": {
      "optimized": true,
      "services": [
        "logger",
        "rpc"
      ]
    },
    "inputSchemaName": "RpcTestInput",
    "outputSchemaName": null,
    "inputs": [
      "RpcTestInput"
    ],
    "outputs": [],
    "expose": true,
    "isDirectFunction": false
  },
  "rpcCaller": {
    "pikkuFuncName": "rpcCaller",
    "name": "rpcCaller",
    "services": {
      "optimized": true,
      "services": [
        "rpc"
      ]
    },
    "inputSchemaName": "RpcCallerInput",
    "outputSchemaName": null,
    "inputs": [
      "RpcCallerInput"
    ],
    "outputs": [],
    "isDirectFunction": false
  },
  "pikkuFn_rpc_wiring_ts_L35C9": {
    "pikkuFuncName": "pikkuFn_rpc_wiring_ts_L35C9",
    "name": "pikkuFn_rpc_wiring_ts_L35C9",
    "services": {
      "optimized": true,
      "services": []
    },
    "inputSchemaName": null,
    "outputSchemaName": null,
    "inputs": [],
    "outputs": [],
    "isDirectFunction": true
  }
})