/**
 * This file was generated by @pikku/cli@0.11.1
 */
import { addSchema } from '@pikku/core/schema'

import * as RpcTestInput from './schemas/RpcTestInput.schema.json' with { type: 'json' }
addSchema('RpcTestInput', RpcTestInput)


import * as RpcCallerInput from './schemas/RpcCallerInput.schema.json' with { type: 'json' }
addSchema('RpcCallerInput', RpcCallerInput)
