/**
 * This file was generated by the @pikku/cli
 */
import { addSchema } from '@pikku/core/schema'

import * as TimeSinceOpenedOutput from './schemas/TimeSinceOpenedOutput.schema.json' with { type: 'json' }
addSchema('TimeSinceOpenedOutput', TimeSinceOpenedOutput)


import * as RpcTestInput from './schemas/RpcTestInput.schema.json' with { type: 'json' }
addSchema('RpcTestInput', RpcTestInput)


import * as RpcCallerInput from './schemas/RpcCallerInput.schema.json' with { type: 'json' }
addSchema('RpcCallerInput', RpcCallerInput)
