/**
 * This file was generated by @pikku/cli@0.12.15
 */
import { addSchema } from '@pikku/core/schema'

import * as ListTodosInput from './schemas/ListTodosInput.schema.json' with { type: 'json' }
addSchema('ListTodosInput', ListTodosInput)


import * as ListTodosOutput from './schemas/ListTodosOutput.schema.json' with { type: 'json' }
addSchema('ListTodosOutput', ListTodosOutput)


import * as GetTodoInput from './schemas/GetTodoInput.schema.json' with { type: 'json' }
addSchema('GetTodoInput', GetTodoInput)


import * as GetTodoOutput from './schemas/GetTodoOutput.schema.json' with { type: 'json' }
addSchema('GetTodoOutput', GetTodoOutput)


import * as CreateTodoInput from './schemas/CreateTodoInput.schema.json' with { type: 'json' }
addSchema('CreateTodoInput', CreateTodoInput)


import * as CreateTodoOutput from './schemas/CreateTodoOutput.schema.json' with { type: 'json' }
addSchema('CreateTodoOutput', CreateTodoOutput)


import * as UpdateTodoInput from './schemas/UpdateTodoInput.schema.json' with { type: 'json' }
addSchema('UpdateTodoInput', UpdateTodoInput)


import * as UpdateTodoOutput from './schemas/UpdateTodoOutput.schema.json' with { type: 'json' }
addSchema('UpdateTodoOutput', UpdateTodoOutput)


import * as DeleteTodoInput from './schemas/DeleteTodoInput.schema.json' with { type: 'json' }
addSchema('DeleteTodoInput', DeleteTodoInput)


import * as DeleteTodoOutput from './schemas/DeleteTodoOutput.schema.json' with { type: 'json' }
addSchema('DeleteTodoOutput', DeleteTodoOutput)


import * as CompleteTodoInput from './schemas/CompleteTodoInput.schema.json' with { type: 'json' }
addSchema('CompleteTodoInput', CompleteTodoInput)


import * as CompleteTodoOutput from './schemas/CompleteTodoOutput.schema.json' with { type: 'json' }
addSchema('CompleteTodoOutput', CompleteTodoOutput)


import * as TestEventTriggerInput from './schemas/TestEventTriggerInput.schema.json' with { type: 'json' }
addSchema('TestEventTriggerInput', TestEventTriggerInput)


import * as TestEventTriggerOutput from './schemas/TestEventTriggerOutput.schema.json' with { type: 'json' }
addSchema('TestEventTriggerOutput', TestEventTriggerOutput)


import * as OnTestEventInput from './schemas/OnTestEventInput.schema.json' with { type: 'json' }
addSchema('OnTestEventInput', OnTestEventInput)


import * as OnTestEventOutput from './schemas/OnTestEventOutput.schema.json' with { type: 'json' }
addSchema('OnTestEventOutput', OnTestEventOutput)


import * as RpcCallerInput from './schemas/RpcCallerInput.schema.json' with { type: 'json' }
addSchema('RpcCallerInput', RpcCallerInput)


import * as HttpOptionsRpcRpcNameInput from './schemas/HttpOptionsRpcRpcNameInput.schema.json' with { type: 'json' }
addSchema('HttpOptionsRpcRpcNameInput', HttpOptionsRpcRpcNameInput)


import * as AgentCallerInput from './schemas/AgentCallerInput.schema.json' with { type: 'json' }
addSchema('AgentCallerInput', AgentCallerInput)


import * as AgentStreamCallerInput from './schemas/AgentStreamCallerInput.schema.json' with { type: 'json' }
addSchema('AgentStreamCallerInput', AgentStreamCallerInput)


import * as AgentApproveCallerInput from './schemas/AgentApproveCallerInput.schema.json' with { type: 'json' }
addSchema('AgentApproveCallerInput', AgentApproveCallerInput)


import * as AgentResumeCallerInput from './schemas/AgentResumeCallerInput.schema.json' with { type: 'json' }
addSchema('AgentResumeCallerInput', AgentResumeCallerInput)


import * as TodoAssistantOutput from './schemas/TodoAssistantOutput.schema.json' with { type: 'json' }
addSchema('TodoAssistantOutput', TodoAssistantOutput)
